data_loader:
  name: "T_Less"
  input_size: 224
  config:
    dataset_path: "datasets/t-less_v2"
    dirs: ["train_kinect/01"]
    hdf5: "tless.hdf5"
    biterion: False
    blur: False
train:
  loss_function: "bingham" # deepvo_mse, deepvo_prob, deepvo_bingham_fixed_z, deepvo_bingham
  loss_parameters:
    lookup_table_file: "precomputed/lookup_-500_0_40.dill"
    orthogonalization: "gram_schmidt"
  device: "cuda:0"
  num_outputs: 19
  num_epochs: 5
  num_channels: 3
  batch_size: 1 
  learning_rate: 0.0001
  model: "resnet18"
  save_as: "tless/bd_5"
  save_dir: "models/tless/bd_5"
  resume: False
